name: heroku

on:
    push:
        branches:
            - master
        # paths:
        #     - '.github/workflows/server.yml'

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2.0.0
            - uses: actions/setup-node@v1.1.0
              with:
                  version: '13.x'
            - name: yarn-cache
              id: yarn-cache
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v1.1.2
              with:
                  path: ${{ steps.yarn-cache.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - run: yarn install
            - run: make test
              env:
                  NODE_ENV: 'development'
                  TG_BOT_NAME: 'bot'
                  TG_BOT_TOKEN: 'TG_BOT_TOKEN'
                  TG_WEBHOOK_DOMAIN: 'www.example.com'
                  TG_WEBHOOK_PATH: '/xxx'
                  ROLLBAR_TOKEN: 'https://rollbar.com'
                  DATABASE_URL: 'postgres://example'
            - name: push to heroku
              run: git push --force https://heroku:$HEROKU_AUTH_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
              env:
                  HEROKU_APP_NAME: 'tg-bcc-bot'
                  HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
